### ISSUE TITLE
Adding Horror Cyphers

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#11]
Attached are the horror cyphers from the CYPHER SYSTEM REFERENCE DOCUMENT 2023-04-18

[horror.zip](https://github.com/Jon-Davis/Cypher-System-JSON-DB/files/11683373/horror.zip)

I felt bad about all the typo/whitespace issues, here's some actual value for you, maybe.

(if you had a formatted version of the .json file, I could push patches up, but with it it's all minified, doesn't seem worthwhile.)

Thanks for all the work!

**Comment by Jon-Davis** [comment]
Thank you! I added the horror cyphers and published my source code so in the future the source files can be updated directly!
