### ISSUE TITLE
0 is the new 100

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#13]
Thoughts on making a tweak to the table data?
Table should end in 100 instead 0?

...
71-80 Vampires
81-90 Werewolves (or some other werecreature)
91-95 Extradimensional creatures
96-00 Undead
...
            {
              "start": 96,
              "end": 0,
              "entry": "Undead"
            }
...

I have a one line work around on my side, but maybe its better to correct that in the parser on yours?

What do you think?

**Comment by Jon-Davis** [comment]
Yeah that's a good call, I just pushed a change to convert any roll table ending in 00 to instead output 100.
