### ISSUE TITLE
SKILL BOOST / WEAPON ENHANCEMENT option tables with zeros

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#14]
build some more data tests, caught a couple of additional zeros in the tables.

these zeros should be 100 instead

SKILL BOOST :{"start"=>0, "end"=>0, "entry"=>"Escaping"} 

WEAPON ENHANCEMENT :{"start"=>0, "end"=>0, "entry"=>"Heart-seeking (on 18-20 on successful attack roll, target is killed)"}

**Comment by Jon-Davis** [comment]
Thanks! fixed!
