### ISSUE TITLE
Missing Creatures

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#23]
Looks like the creatures.md is missing some/most/all of the WAAMH creatures?

I could take a crack at hand copying them into the Creatures.md, but not sure about getting the rust code running to test it?

Worth it for me to take a first run at it, and let you clean it up, or the Creatures.md coming from some other parser that could get tweaked to include the missing ones?

This list is from some other debug scripts trying to match data from a couple of other sources, not the CRSD document itself, so it might not be 100% accurate.

Let me know if you have time to work on these, otherwise I'll do some other work around.
Thanks!

  Aristocrat
  Blob
  Cannibal
  Child
  Crafter
  Cryptic Moth
  Death
  Elder Thing
  Fundamental Angel
  Hivemind Child
  Huntsman/Woodcutter
  Ichthysians
  Mad Scientist
  Mummy
  Natathim (Homo aquus)
  Nightgaunt
  Reanimated
  Robber
  Scholar
  Shoggoth
  Tin Woodman
  Wraith (Homo vacuus)
  Yithian

**Comment by Jon-Davis** [comment]
Thanks for your work with these
