### ISSUE TITLE
Duplicate Names - FAERIE / BOUNDING BOOTS

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#24]
There's not an actual rule here, but my code is hoping that things have unique names.

There's two instances (that I currently know of) where that's broken.

There are two entries for FAERIE and two entries for BOUNDING BOOTS.

They're appearing in the core CSRD and then they're (mostly) replicated under the WAAMH setting also in the CSRD.

I see you've done some things like WRAITH (STARS ARE FIRE) to handle this before, is that an approach?

Let me know if that's something you'd entertain, otherwise I'll tweak things on my side to unique them when I'm processing the data.

Thanks!

**Comment by Jon-Davis** [comment]
Yeah, tentatively I think the best way to handle things is to have unique names, where duplicates are mentioned in parentheses.
