### ISSUE TITLE
Parsing error: Camera (Equipment)

### ISSUE THREAD

**Issue by isaaclyman** [Jon-Davis/Cypher-System-JSON-DB#28]
Thanks for your hard work on this! I'm currently working on a mobile app for SRD search/lookup that uses this JSON as a data source.

I've noticed a parsing error with the Camera entry. In CSRD.json:

```json
{"name":"Camera","variants":[{"description":"designed to be concealed Transmits at long range." ...
```

Should be:

```json
{"name":"Camera designed to be concealed","variants":[{"description":"Transmits at long range." ...
```

**Comment by Jon-Davis** [comment]
fixed
