### ISSUE TITLE
Minor Case Sensitivity - Built-In Weaponry vs Built-in Weaponry

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#5]
This is minor but mentioning it as I find things.

Thanks again!

Given we have to match things on names, it would be 'handy' if these strings matched each other in case for the name attribute.

      "name": "CRAFTS UNIQUE OBJECTS",
...
        {
          "name": "Built-In Weaponry",
          "tier": 3,
          "preselected": false
        },
...

    {
      "name": "Built-in Weaponry",
      "cost": null,
      "pool": [],
      "additional_cost": null,
      "tier": "Mid",
      "category": [
        "SPECIAL ATTACK"
      ],
      "description": "Biomechanical implants, a magical jewel fused to your forehead, or something just as wild now provides you with inherent weaponry. This allows you to fire a blast of energy up to long range that inflicts 5 points of damage. There is no cost for you to use this ability. Action.",
      "references": [
        "CRAFTS UNIQUE OBJECTS"
      ]
    },

**Comment by Jon-Davis** [comment]
I updated the focus to be in line with the ability styling, Thanks!
