### ISSUE TITLE
WEILDS AN ENCHANTED WEAPON

### ISSUE THREAD

**Issue by davebytemfg** [Jon-Davis/Cypher-System-JSON-DB#7]
Near as I can tell the CSOL document is wrong, so unclear what the policy should be, but googling indicates that WEILDS isn't a word. 

So maybe just an FYI?

```
-      "name": "WEILDS AN ENCHANTED WEAPON",
+      "name": "WIELDS AN ENCHANTED WEAPON",
       "description": "You have a weapon with strange abilities, and your knowledge of its powers has allowed you to create a unique style of combat with it.",
       "abilities": [
```

there's a variety of references to it as well.

```
       "references": [
-        "WEILDS AN ENCHANTED WEAPON"
+        "WIELDS AN ENCHANTED WEAPON"
       ]
```

**Comment by Jon-Davis** [comment]
Yeah usually I stick the CSOL but spelling mistakes are something I'm ok with fixing. Thanks!
